-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity decoder_decoder_Pipeline_decoder_label0 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    num1_cast : IN STD_LOGIC_VECTOR (30 downto 0);
    p_Result_14 : IN STD_LOGIC_VECTOR (0 downto 0);
    cnt1_out : OUT STD_LOGIC_VECTOR (4 downto 0);
    cnt1_out_ap_vld : OUT STD_LOGIC;
    in_1_out : OUT STD_LOGIC_VECTOR (5 downto 0);
    in_1_out_ap_vld : OUT STD_LOGIC;
    ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of decoder_decoder_Pipeline_decoder_label0 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_1E : STD_LOGIC_VECTOR (5 downto 0) := "011110";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal xor_ln951_fu_158_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_122_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_phi_mux_UnifiedRetVal_phi_fu_96_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal in_1_fu_58 : STD_LOGIC_VECTOR (5 downto 0);
    signal in_1_3_fu_164_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_in_1_2 : STD_LOGIC_VECTOR (5 downto 0);
    signal cnt1_fu_62 : STD_LOGIC_VECTOR (4 downto 0);
    signal cnt1_2_fu_130_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_cnt1_1 : STD_LOGIC_VECTOR (4 downto 0);
    signal in_1_cast_fu_136_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal shl_ln961_fu_140_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal and_ln961_fu_146_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal p_Result_s_fu_152_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component decoder_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component decoder_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv1_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1) and ((tmp_fu_122_p3 = ap_const_lv1_1) or (xor_ln951_fu_158_p2 = ap_const_lv1_1)))) then 
                    ap_return_preg <= ap_phi_mux_UnifiedRetVal_phi_fu_96_p4;
                end if; 
            end if;
        end if;
    end process;


    cnt1_fu_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then
                if (((tmp_fu_122_p3 = ap_const_lv1_0) and (xor_ln951_fu_158_p2 = ap_const_lv1_0))) then 
                    cnt1_fu_62 <= cnt1_2_fu_130_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    cnt1_fu_62 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    in_1_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then
                if (((tmp_fu_122_p3 = ap_const_lv1_0) and (xor_ln951_fu_158_p2 = ap_const_lv1_0))) then 
                    in_1_fu_58 <= in_1_3_fu_164_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    in_1_fu_58 <= ap_const_lv6_1E;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    and_ln961_fu_146_p2 <= (shl_ln961_fu_140_p2 and num1_cast);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start_int)
    begin
        if ((ap_start_int = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, xor_ln951_fu_158_p2, tmp_fu_122_p3, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1) and ((tmp_fu_122_p3 = ap_const_lv1_1) or (xor_ln951_fu_158_p2 = ap_const_lv1_1)))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_loop_exit_ready, ap_done_reg, ap_start_int)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_UnifiedRetVal_phi_fu_96_p4_assign_proc : process(ap_CS_fsm_state1, xor_ln951_fu_158_p2, tmp_fu_122_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
            if (((tmp_fu_122_p3 = ap_const_lv1_0) and (xor_ln951_fu_158_p2 = ap_const_lv1_1))) then 
                ap_phi_mux_UnifiedRetVal_phi_fu_96_p4 <= ap_const_lv1_0;
            elsif ((tmp_fu_122_p3 = ap_const_lv1_1)) then 
                ap_phi_mux_UnifiedRetVal_phi_fu_96_p4 <= ap_const_lv1_1;
            else 
                ap_phi_mux_UnifiedRetVal_phi_fu_96_p4 <= "X";
            end if;
        else 
            ap_phi_mux_UnifiedRetVal_phi_fu_96_p4 <= "X";
        end if; 
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(ap_CS_fsm_state1, xor_ln951_fu_158_p2, tmp_fu_122_p3, ap_phi_mux_UnifiedRetVal_phi_fu_96_p4, ap_return_preg, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1) and ((tmp_fu_122_p3 = ap_const_lv1_1) or (xor_ln951_fu_158_p2 = ap_const_lv1_1)))) then 
            ap_return <= ap_phi_mux_UnifiedRetVal_phi_fu_96_p4;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;


    ap_sig_allocacmp_cnt1_1_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, cnt1_fu_62)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_cnt1_1 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_cnt1_1 <= cnt1_fu_62;
        end if; 
    end process;


    ap_sig_allocacmp_in_1_2_assign_proc : process(ap_CS_fsm_state1, in_1_fu_58, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_in_1_2 <= ap_const_lv6_1E;
        else 
            ap_sig_allocacmp_in_1_2 <= in_1_fu_58;
        end if; 
    end process;

    cnt1_2_fu_130_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_cnt1_1) + unsigned(ap_const_lv5_1));
    cnt1_out <= ap_sig_allocacmp_cnt1_1;

    cnt1_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, xor_ln951_fu_158_p2, tmp_fu_122_p3, ap_start_int)
    begin
        if ((((tmp_fu_122_p3 = ap_const_lv1_0) and (xor_ln951_fu_158_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1)) or ((tmp_fu_122_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1)))) then 
            cnt1_out_ap_vld <= ap_const_logic_1;
        else 
            cnt1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    in_1_3_fu_164_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_in_1_2) + unsigned(ap_const_lv6_3F));
    in_1_cast_fu_136_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_in_1_2),31));

    in_1_out_assign_proc : process(ap_CS_fsm_state1, xor_ln951_fu_158_p2, tmp_fu_122_p3, ap_sig_allocacmp_in_1_2, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then
            if ((tmp_fu_122_p3 = ap_const_lv1_1)) then 
                in_1_out <= ap_const_lv6_3F;
            elsif (((tmp_fu_122_p3 = ap_const_lv1_0) and (xor_ln951_fu_158_p2 = ap_const_lv1_1))) then 
                in_1_out <= ap_sig_allocacmp_in_1_2;
            else 
                in_1_out <= "XXXXXX";
            end if;
        else 
            in_1_out <= "XXXXXX";
        end if; 
    end process;


    in_1_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, xor_ln951_fu_158_p2, tmp_fu_122_p3, ap_start_int)
    begin
        if ((((tmp_fu_122_p3 = ap_const_lv1_0) and (xor_ln951_fu_158_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1)) or ((tmp_fu_122_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1)))) then 
            in_1_out_ap_vld <= ap_const_logic_1;
        else 
            in_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_Result_s_fu_152_p2 <= "0" when (and_ln961_fu_146_p2 = ap_const_lv31_0) else "1";
    shl_ln961_fu_140_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv31_1),to_integer(unsigned('0' & in_1_cast_fu_136_p1(31-1 downto 0)))));
    tmp_fu_122_p3 <= ap_sig_allocacmp_in_1_2(5 downto 5);
    xor_ln951_fu_158_p2 <= (p_Result_s_fu_152_p2 xor p_Result_14);
end behav;
