// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="decoder_decoder,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a12ti-csg325-1L,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.197069,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=5,HLS_SYN_DSP=0,HLS_SYN_FF=9449,HLS_SYN_LUT=16816,HLS_VERSION=2022_2}" *)

module decoder (
        ap_clk,
        ap_rst,
        num1,
        num2,
        ap_return
);

parameter    ap_ST_fsm_state1 = 48'd1;
parameter    ap_ST_fsm_state2 = 48'd2;
parameter    ap_ST_fsm_state3 = 48'd4;
parameter    ap_ST_fsm_state4 = 48'd8;
parameter    ap_ST_fsm_state5 = 48'd16;
parameter    ap_ST_fsm_state6 = 48'd32;
parameter    ap_ST_fsm_state7 = 48'd64;
parameter    ap_ST_fsm_state8 = 48'd128;
parameter    ap_ST_fsm_state9 = 48'd256;
parameter    ap_ST_fsm_state10 = 48'd512;
parameter    ap_ST_fsm_state11 = 48'd1024;
parameter    ap_ST_fsm_state12 = 48'd2048;
parameter    ap_ST_fsm_state13 = 48'd4096;
parameter    ap_ST_fsm_state14 = 48'd8192;
parameter    ap_ST_fsm_state15 = 48'd16384;
parameter    ap_ST_fsm_state16 = 48'd32768;
parameter    ap_ST_fsm_state17 = 48'd65536;
parameter    ap_ST_fsm_state18 = 48'd131072;
parameter    ap_ST_fsm_state19 = 48'd262144;
parameter    ap_ST_fsm_state20 = 48'd524288;
parameter    ap_ST_fsm_state21 = 48'd1048576;
parameter    ap_ST_fsm_state22 = 48'd2097152;
parameter    ap_ST_fsm_state23 = 48'd4194304;
parameter    ap_ST_fsm_state24 = 48'd8388608;
parameter    ap_ST_fsm_state25 = 48'd16777216;
parameter    ap_ST_fsm_state26 = 48'd33554432;
parameter    ap_ST_fsm_state27 = 48'd67108864;
parameter    ap_ST_fsm_state28 = 48'd134217728;
parameter    ap_ST_fsm_state29 = 48'd268435456;
parameter    ap_ST_fsm_state30 = 48'd536870912;
parameter    ap_ST_fsm_state31 = 48'd1073741824;
parameter    ap_ST_fsm_state32 = 48'd2147483648;
parameter    ap_ST_fsm_state33 = 48'd4294967296;
parameter    ap_ST_fsm_state34 = 48'd8589934592;
parameter    ap_ST_fsm_state35 = 48'd17179869184;
parameter    ap_ST_fsm_state36 = 48'd34359738368;
parameter    ap_ST_fsm_state37 = 48'd68719476736;
parameter    ap_ST_fsm_state38 = 48'd137438953472;
parameter    ap_ST_fsm_state39 = 48'd274877906944;
parameter    ap_ST_fsm_state40 = 48'd549755813888;
parameter    ap_ST_fsm_state41 = 48'd1099511627776;
parameter    ap_ST_fsm_state42 = 48'd2199023255552;
parameter    ap_ST_fsm_state43 = 48'd4398046511104;
parameter    ap_ST_fsm_state44 = 48'd8796093022208;
parameter    ap_ST_fsm_state45 = 48'd17592186044416;
parameter    ap_ST_fsm_state46 = 48'd35184372088832;
parameter    ap_ST_fsm_state47 = 48'd70368744177664;
parameter    ap_ST_fsm_state48 = 48'd140737488355328;

input   ap_clk;
input   ap_rst;
input  [31:0] num1;
input  [31:0] num2;
output  [31:0] ap_return;

wire   [63:0] grp_fu_435_p1;
reg   [63:0] reg_441;
(* fsm_encoding = "none" *) reg   [47:0] ap_CS_fsm;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state16;
wire   [63:0] grp_fu_438_p1;
reg   [63:0] reg_447;
wire    ap_CS_fsm_state1;
wire   [30:0] empty_fu_453_p1;
reg   [30:0] empty_reg_1424;
wire   [30:0] empty_51_fu_458_p1;
reg   [30:0] empty_51_reg_1429;
reg   [0:0] p_Result_s_reg_1434;
reg   [0:0] p_Result_55_reg_1440;
wire   [0:0] grp_decoder_Pipeline_decoder_label0_fu_293_ap_return;
reg   [0:0] targetBlock_reg_1446;
wire    ap_CS_fsm_state2;
wire   [0:0] grp_decoder_Pipeline_decoder_label1_fu_301_ap_return;
reg   [0:0] targetBlock8_reg_1451;
wire  signed [5:0] k1_2_fu_514_p3;
reg  signed [5:0] k1_2_reg_1456;
wire    ap_CS_fsm_state3;
wire   [1:0] expo1_V_fu_540_p1;
reg   [1:0] expo1_V_reg_1463;
wire   [27:0] p_Result_67_fu_600_p2;
reg   [27:0] p_Result_67_reg_1470;
wire   [1:0] expo2_V_fu_647_p1;
reg   [1:0] expo2_V_reg_1475;
wire   [27:0] p_Result_69_fu_706_p2;
reg   [27:0] p_Result_69_reg_1482;
wire  signed [5:0] k2_4_fu_725_p3;
reg  signed [5:0] k2_4_reg_1487;
wire  signed [31:0] sext_ln125_fu_732_p1;
wire    ap_CS_fsm_state4;
wire  signed [31:0] sext_ln126_fu_736_p1;
wire   [63:0] grp_fu_425_p2;
reg   [63:0] mul2_reg_1510;
wire   [63:0] grp_fu_430_p2;
reg   [63:0] mul3_reg_1515;
wire   [63:0] grp_fu_417_p2;
reg   [63:0] dc_reg_1520;
wire    ap_CS_fsm_state24;
wire   [63:0] grp_fu_421_p2;
reg   [63:0] dc_1_reg_1525;
reg   [0:0] p_Result_70_reg_1530;
wire    ap_CS_fsm_state25;
wire   [31:0] val_fu_865_p3;
reg   [31:0] val_reg_1535;
reg   [0:0] p_Result_72_reg_1541;
wire   [31:0] val_1_fu_990_p3;
reg   [31:0] val_1_reg_1546;
wire   [31:0] exp1_conv_fu_1011_p3;
reg   [31:0] exp1_conv_reg_1558;
wire    ap_CS_fsm_state26;
wire   [31:0] exp2_conv_fu_1022_p3;
reg   [31:0] exp2_conv_reg_1564;
wire   [0:0] icmp_ln147_fu_1028_p2;
reg   [0:0] icmp_ln147_reg_1570;
wire   [0:0] icmp_ln175_fu_1034_p2;
reg   [0:0] icmp_ln175_reg_1574;
wire   [0:0] icmp_ln216_fu_1040_p2;
reg   [0:0] icmp_ln216_reg_1578;
wire   [1:0] exponent_arr_V_1_fu_1050_p3;
wire    ap_CS_fsm_state30;
wire   [31:0] j_20_fu_1060_p2;
reg   [31:0] j_20_reg_1594;
wire    ap_CS_fsm_state31;
wire   [31:0] j_fu_1091_p2;
reg   [31:0] j_reg_1602;
wire    ap_CS_fsm_state36;
reg   [0:0] carry_V_1_loc_load_reg_1613;
wire    ap_CS_fsm_state41;
wire   [5:0] k_final_fu_1111_p3;
reg   [5:0] k_final_reg_1617;
wire   [0:0] tmp_29_fu_1121_p3;
reg   [0:0] tmp_29_reg_1622;
wire   [5:0] k_final_1_fu_1129_p2;
reg   [5:0] k_final_1_reg_1626;
wire   [4:0] trunc_ln256_1_fu_1135_p1;
reg   [4:0] trunc_ln256_1_reg_1631;
wire   [4:0] sub228_fu_1140_p2;
reg   [4:0] sub228_reg_1636;
wire  signed [6:0] opposite_bit_index_final_fu_1177_p2;
reg  signed [6:0] opposite_bit_index_final_reg_1647;
wire    ap_CS_fsm_state43;
wire   [4:0] trunc_ln297_fu_1183_p1;
reg   [4:0] trunc_ln297_reg_1653;
wire   [6:0] j_22_fu_1214_p2;
reg   [6:0] j_22_reg_1658;
wire    ap_CS_fsm_state45;
wire   [31:0] p_Result_75_fu_1258_p2;
reg   [31:0] p_Result_75_reg_1664;
wire   [28:0] r_V_26_fu_1266_p2;
reg   [28:0] r_V_26_reg_1670;
wire    grp_decoder_Pipeline_decoder_label0_fu_293_ap_start;
wire    grp_decoder_Pipeline_decoder_label0_fu_293_ap_done;
wire    grp_decoder_Pipeline_decoder_label0_fu_293_ap_idle;
wire    grp_decoder_Pipeline_decoder_label0_fu_293_ap_ready;
wire   [4:0] grp_decoder_Pipeline_decoder_label0_fu_293_cnt1_out;
wire    grp_decoder_Pipeline_decoder_label0_fu_293_cnt1_out_ap_vld;
wire   [5:0] grp_decoder_Pipeline_decoder_label0_fu_293_in_1_out;
wire    grp_decoder_Pipeline_decoder_label0_fu_293_in_1_out_ap_vld;
wire    grp_decoder_Pipeline_decoder_label1_fu_301_ap_start;
wire    grp_decoder_Pipeline_decoder_label1_fu_301_ap_done;
wire    grp_decoder_Pipeline_decoder_label1_fu_301_ap_idle;
wire    grp_decoder_Pipeline_decoder_label1_fu_301_ap_ready;
wire   [4:0] grp_decoder_Pipeline_decoder_label1_fu_301_cnt2_out;
wire    grp_decoder_Pipeline_decoder_label1_fu_301_cnt2_out_ap_vld;
wire   [5:0] grp_decoder_Pipeline_decoder_label1_fu_301_in_2_out;
wire    grp_decoder_Pipeline_decoder_label1_fu_301_in_2_out_ap_vld;
wire    grp_decoder_Pipeline_decoder_label2_fu_309_ap_start;
wire    grp_decoder_Pipeline_decoder_label2_fu_309_ap_done;
wire    grp_decoder_Pipeline_decoder_label2_fu_309_ap_idle;
wire    grp_decoder_Pipeline_decoder_label2_fu_309_ap_ready;
wire   [31:0] grp_decoder_Pipeline_decoder_label2_fu_309_exponent1_out;
wire    grp_decoder_Pipeline_decoder_label2_fu_309_exponent1_out_ap_vld;
wire   [63:0] grp_decoder_Pipeline_decoder_label2_fu_309_grp_fu_417_p_din0;
wire   [63:0] grp_decoder_Pipeline_decoder_label2_fu_309_grp_fu_417_p_din1;
wire   [1:0] grp_decoder_Pipeline_decoder_label2_fu_309_grp_fu_417_p_opcode;
wire    grp_decoder_Pipeline_decoder_label2_fu_309_grp_fu_417_p_ce;
wire   [63:0] grp_decoder_Pipeline_decoder_label2_fu_309_grp_fu_425_p_din0;
wire   [63:0] grp_decoder_Pipeline_decoder_label2_fu_309_grp_fu_425_p_din1;
wire    grp_decoder_Pipeline_decoder_label2_fu_309_grp_fu_425_p_ce;
wire   [31:0] grp_decoder_Pipeline_decoder_label2_fu_309_grp_fu_1675_p_din0;
wire    grp_decoder_Pipeline_decoder_label2_fu_309_grp_fu_1675_p_ce;
wire   [63:0] grp_decoder_Pipeline_decoder_label2_fu_309_grp_pow_generic_double_s_fu_1678_p_din1;
wire    grp_decoder_Pipeline_decoder_label2_fu_309_grp_pow_generic_double_s_fu_1678_p_start;
wire    grp_decoder_Pipeline_decoder_label4_fu_321_ap_start;
wire    grp_decoder_Pipeline_decoder_label4_fu_321_ap_done;
wire    grp_decoder_Pipeline_decoder_label4_fu_321_ap_idle;
wire    grp_decoder_Pipeline_decoder_label4_fu_321_ap_ready;
wire   [28:0] grp_decoder_Pipeline_decoder_label4_fu_321_mant2_new_V_1_out;
wire    grp_decoder_Pipeline_decoder_label4_fu_321_mant2_new_V_1_out_ap_vld;
wire   [28:0] grp_decoder_Pipeline_decoder_label4_fu_321_mant1_new_V_1_out;
wire    grp_decoder_Pipeline_decoder_label4_fu_321_mant1_new_V_1_out_ap_vld;
wire    grp_decoder_Pipeline_decoder_label3_fu_329_ap_start;
wire    grp_decoder_Pipeline_decoder_label3_fu_329_ap_done;
wire    grp_decoder_Pipeline_decoder_label3_fu_329_ap_idle;
wire    grp_decoder_Pipeline_decoder_label3_fu_329_ap_ready;
wire   [31:0] grp_decoder_Pipeline_decoder_label3_fu_329_exponent2_out;
wire    grp_decoder_Pipeline_decoder_label3_fu_329_exponent2_out_ap_vld;
wire   [63:0] grp_decoder_Pipeline_decoder_label3_fu_329_grp_fu_417_p_din0;
wire   [63:0] grp_decoder_Pipeline_decoder_label3_fu_329_grp_fu_417_p_din1;
wire   [1:0] grp_decoder_Pipeline_decoder_label3_fu_329_grp_fu_417_p_opcode;
wire    grp_decoder_Pipeline_decoder_label3_fu_329_grp_fu_417_p_ce;
wire   [63:0] grp_decoder_Pipeline_decoder_label3_fu_329_grp_fu_425_p_din0;
wire   [63:0] grp_decoder_Pipeline_decoder_label3_fu_329_grp_fu_425_p_din1;
wire    grp_decoder_Pipeline_decoder_label3_fu_329_grp_fu_425_p_ce;
wire   [31:0] grp_decoder_Pipeline_decoder_label3_fu_329_grp_fu_1675_p_din0;
wire    grp_decoder_Pipeline_decoder_label3_fu_329_grp_fu_1675_p_ce;
wire   [63:0] grp_decoder_Pipeline_decoder_label3_fu_329_grp_pow_generic_double_s_fu_1678_p_din1;
wire    grp_decoder_Pipeline_decoder_label3_fu_329_grp_pow_generic_double_s_fu_1678_p_start;
wire    grp_decoder_Pipeline_decoder_label9_fu_341_ap_start;
wire    grp_decoder_Pipeline_decoder_label9_fu_341_ap_done;
wire    grp_decoder_Pipeline_decoder_label9_fu_341_ap_idle;
wire    grp_decoder_Pipeline_decoder_label9_fu_341_ap_ready;
wire   [28:0] grp_decoder_Pipeline_decoder_label9_fu_341_mant2_final_V_8_out;
wire    grp_decoder_Pipeline_decoder_label9_fu_341_mant2_final_V_8_out_ap_vld;
wire   [28:0] grp_decoder_Pipeline_decoder_label9_fu_341_mant1_final_V_8_out;
wire    grp_decoder_Pipeline_decoder_label9_fu_341_mant1_final_V_8_out_ap_vld;
wire    grp_decoder_Pipeline_decoder_label7_fu_349_ap_start;
wire    grp_decoder_Pipeline_decoder_label7_fu_349_ap_done;
wire    grp_decoder_Pipeline_decoder_label7_fu_349_ap_idle;
wire    grp_decoder_Pipeline_decoder_label7_fu_349_ap_ready;
wire   [28:0] grp_decoder_Pipeline_decoder_label7_fu_349_mant1_new_new_V_1_out;
wire    grp_decoder_Pipeline_decoder_label7_fu_349_mant1_new_new_V_1_out_ap_vld;
wire    grp_decoder_Pipeline_decoder_label8_fu_356_ap_start;
wire    grp_decoder_Pipeline_decoder_label8_fu_356_ap_done;
wire    grp_decoder_Pipeline_decoder_label8_fu_356_ap_idle;
wire    grp_decoder_Pipeline_decoder_label8_fu_356_ap_ready;
wire   [28:0] grp_decoder_Pipeline_decoder_label8_fu_356_mant2_final_V_7_out;
wire    grp_decoder_Pipeline_decoder_label8_fu_356_mant2_final_V_7_out_ap_vld;
wire   [28:0] grp_decoder_Pipeline_decoder_label8_fu_356_mant1_final_V_7_out;
wire    grp_decoder_Pipeline_decoder_label8_fu_356_mant1_final_V_7_out_ap_vld;
wire    grp_decoder_Pipeline_decoder_label10_fu_364_ap_start;
wire    grp_decoder_Pipeline_decoder_label10_fu_364_ap_done;
wire    grp_decoder_Pipeline_decoder_label10_fu_364_ap_idle;
wire    grp_decoder_Pipeline_decoder_label10_fu_364_ap_ready;
wire   [28:0] grp_decoder_Pipeline_decoder_label10_fu_364_sum_V_2_out;
wire    grp_decoder_Pipeline_decoder_label10_fu_364_sum_V_2_out_ap_vld;
wire   [0:0] grp_decoder_Pipeline_decoder_label10_fu_364_carry_V_1_out;
wire    grp_decoder_Pipeline_decoder_label10_fu_364_carry_V_1_out_ap_vld;
wire    grp_decoder_Pipeline_decoder_label5_fu_374_ap_start;
wire    grp_decoder_Pipeline_decoder_label5_fu_374_ap_done;
wire    grp_decoder_Pipeline_decoder_label5_fu_374_ap_idle;
wire    grp_decoder_Pipeline_decoder_label5_fu_374_ap_ready;
wire   [28:0] grp_decoder_Pipeline_decoder_label5_fu_374_mant2_new_new_V_1_out;
wire    grp_decoder_Pipeline_decoder_label5_fu_374_mant2_new_new_V_1_out_ap_vld;
wire    grp_decoder_Pipeline_decoder_label6_fu_381_ap_start;
wire    grp_decoder_Pipeline_decoder_label6_fu_381_ap_done;
wire    grp_decoder_Pipeline_decoder_label6_fu_381_ap_idle;
wire    grp_decoder_Pipeline_decoder_label6_fu_381_ap_ready;
wire   [28:0] grp_decoder_Pipeline_decoder_label6_fu_381_mant2_final_V_out;
wire    grp_decoder_Pipeline_decoder_label6_fu_381_mant2_final_V_out_ap_vld;
wire   [28:0] grp_decoder_Pipeline_decoder_label6_fu_381_mant1_final_V_out;
wire    grp_decoder_Pipeline_decoder_label6_fu_381_mant1_final_V_out_ap_vld;
wire    grp_decoder_Pipeline_decoder_label12_fu_389_ap_start;
wire    grp_decoder_Pipeline_decoder_label12_fu_389_ap_done;
wire    grp_decoder_Pipeline_decoder_label12_fu_389_ap_idle;
wire    grp_decoder_Pipeline_decoder_label12_fu_389_ap_ready;
wire   [31:0] grp_decoder_Pipeline_decoder_label12_fu_389_result_V_26_out;
wire    grp_decoder_Pipeline_decoder_label12_fu_389_result_V_26_out_ap_vld;
wire    grp_decoder_Pipeline_decoder_label11_fu_395_ap_start;
wire    grp_decoder_Pipeline_decoder_label11_fu_395_ap_done;
wire    grp_decoder_Pipeline_decoder_label11_fu_395_ap_idle;
wire    grp_decoder_Pipeline_decoder_label11_fu_395_ap_ready;
wire   [31:0] grp_decoder_Pipeline_decoder_label11_fu_395_result_V_25_out;
wire    grp_decoder_Pipeline_decoder_label11_fu_395_result_V_25_out_ap_vld;
wire    grp_decoder_Pipeline_decoder_label14_fu_401_ap_start;
wire    grp_decoder_Pipeline_decoder_label14_fu_401_ap_done;
wire    grp_decoder_Pipeline_decoder_label14_fu_401_ap_idle;
wire    grp_decoder_Pipeline_decoder_label14_fu_401_ap_ready;
wire   [31:0] grp_decoder_Pipeline_decoder_label14_fu_401_result_V_29_out;
wire    grp_decoder_Pipeline_decoder_label14_fu_401_result_V_29_out_ap_vld;
wire    grp_decoder_Pipeline_decoder_label13_fu_409_ap_start;
wire    grp_decoder_Pipeline_decoder_label13_fu_409_ap_done;
wire    grp_decoder_Pipeline_decoder_label13_fu_409_ap_idle;
wire    grp_decoder_Pipeline_decoder_label13_fu_409_ap_ready;
wire   [31:0] grp_decoder_Pipeline_decoder_label13_fu_409_result_V_28_out;
wire    grp_decoder_Pipeline_decoder_label13_fu_409_result_V_28_out_ap_vld;
reg    grp_pow_generic_double_s_fu_1678_ap_start;
wire    grp_pow_generic_double_s_fu_1678_ap_done;
wire    grp_pow_generic_double_s_fu_1678_ap_idle;
wire    grp_pow_generic_double_s_fu_1678_ap_ready;
reg   [63:0] grp_pow_generic_double_s_fu_1678_exp;
wire   [63:0] grp_pow_generic_double_s_fu_1678_ap_return;
reg   [28:0] mant1_final_V_reg_230;
wire    ap_CS_fsm_state35;
reg   [28:0] mant2_final_V_reg_242;
reg   [1:0] exponent_arr_V_2_reg_254;
reg   [5:0] ap_phi_mux_k_final_2_phi_fu_269_p4;
reg   [31:0] result_V_reg_275;
reg   [31:0] ap_phi_mux_result_V_9_phi_fu_287_p4;
wire    ap_CS_fsm_state47;
reg    grp_decoder_Pipeline_decoder_label0_fu_293_ap_start_reg;
reg   [4:0] cnt1_loc_fu_214;
reg   [5:0] in_1_loc_fu_210;
reg    grp_decoder_Pipeline_decoder_label1_fu_301_ap_start_reg;
reg   [4:0] cnt2_loc_fu_206;
reg   [5:0] in_2_loc_fu_202;
reg    grp_decoder_Pipeline_decoder_label2_fu_309_ap_start_reg;
reg    grp_decoder_Pipeline_decoder_label4_fu_321_ap_start_reg;
reg    grp_decoder_Pipeline_decoder_label3_fu_329_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_decoder_Pipeline_decoder_label9_fu_341_ap_start_reg;
wire    ap_CS_fsm_state27;
reg    grp_decoder_Pipeline_decoder_label7_fu_349_ap_start_reg;
wire    ap_CS_fsm_state32;
reg    grp_decoder_Pipeline_decoder_label8_fu_356_ap_start_reg;
wire    ap_CS_fsm_state33;
wire    ap_CS_fsm_state34;
reg    grp_decoder_Pipeline_decoder_label10_fu_364_ap_start_reg;
wire    ap_CS_fsm_state40;
reg    grp_decoder_Pipeline_decoder_label5_fu_374_ap_start_reg;
wire    ap_CS_fsm_state37;
reg    grp_decoder_Pipeline_decoder_label6_fu_381_ap_start_reg;
wire    ap_CS_fsm_state38;
wire    ap_CS_fsm_state39;
reg    grp_decoder_Pipeline_decoder_label12_fu_389_ap_start_reg;
wire    ap_CS_fsm_state42;
reg    grp_decoder_Pipeline_decoder_label11_fu_395_ap_start_reg;
wire    ap_CS_fsm_state44;
reg    grp_decoder_Pipeline_decoder_label14_fu_401_ap_start_reg;
wire    ap_CS_fsm_state46;
reg    grp_decoder_Pipeline_decoder_label13_fu_409_ap_start_reg;
wire    ap_CS_fsm_state48;
wire    ap_CS_fsm_state11;
reg   [63:0] grp_fu_417_p0;
reg   [63:0] grp_fu_417_p1;
wire    ap_CS_fsm_state17;
reg   [63:0] grp_fu_425_p0;
reg   [63:0] grp_fu_425_p1;
wire    ap_CS_fsm_state10;
reg  signed [31:0] grp_fu_435_p0;
reg  signed [31:0] grp_fu_438_p0;
wire   [5:0] select_ln40_fu_487_p3;
wire   [5:0] cnt1_cast_fu_494_p1;
wire   [5:0] k1_1_fu_508_p2;
wire   [5:0] k1_fu_502_p2;
wire   [4:0] trunc_ln60_fu_521_p1;
wire   [4:0] add_ln628_fu_525_p2;
wire   [31:0] zext_ln628_fu_531_p1;
wire   [31:0] lshr_ln628_fu_535_p2;
wire   [4:0] trunc_ln779_fu_498_p1;
wire   [4:0] trunc_ln61_fu_545_p1;
wire   [4:0] sub_ln628_fu_555_p2;
wire   [31:0] zext_ln628_1_fu_561_p1;
wire   [31:0] lshr_ln628_1_fu_565_p2;
wire   [31:0] p_Result_66_fu_571_p2;
wire   [4:0] sub_ln66_fu_549_p2;
wire   [27:0] tmp_32_fu_576_p1;
wire   [27:0] zext_ln368_fu_580_p1;
wire   [27:0] zext_ln368_1_fu_584_p1;
wire   [27:0] shl_ln368_fu_588_p2;
wire   [27:0] shl_ln368_1_fu_594_p2;
wire   [5:0] select_ln78_fu_613_p3;
wire   [4:0] trunc_ln98_fu_628_p1;
wire   [4:0] add_ln628_1_fu_632_p2;
wire   [31:0] zext_ln628_2_fu_638_p1;
wire   [31:0] lshr_ln628_2_fu_642_p2;
wire   [4:0] trunc_ln99_fu_651_p1;
wire   [4:0] sub_ln628_1_fu_655_p2;
wire   [31:0] zext_ln628_3_fu_661_p1;
wire   [31:0] lshr_ln628_3_fu_665_p2;
wire   [31:0] p_Result_68_fu_671_p2;
wire   [4:0] trunc_ln779_1_fu_624_p1;
wire   [4:0] sub_ln103_fu_680_p2;
wire   [27:0] tmp_33_fu_676_p1;
wire   [27:0] zext_ln368_2_fu_686_p1;
wire   [27:0] zext_ln368_3_fu_690_p1;
wire   [27:0] shl_ln368_2_fu_694_p2;
wire   [27:0] shl_ln368_3_fu_700_p2;
wire   [5:0] cnt2_cast_fu_620_p1;
wire   [5:0] k2_3_fu_713_p2;
wire   [5:0] k2_fu_719_p2;
wire   [63:0] data_V_fu_748_p1;
wire   [51:0] p_Result_71_fu_769_p1;
wire   [53:0] mantissa_fu_773_p4;
wire   [10:0] xs_exp_V_fu_759_p4;
wire   [11:0] zext_ln515_fu_787_p1;
wire   [11:0] add_ln515_fu_791_p2;
wire   [10:0] sub_ln1512_fu_805_p2;
wire   [0:0] isNeg_fu_797_p3;
wire  signed [11:0] sext_ln1512_fu_811_p1;
wire   [11:0] ush_fu_815_p3;
wire  signed [31:0] sext_ln1488_fu_823_p1;
wire   [136:0] zext_ln15_fu_783_p1;
wire   [136:0] zext_ln1488_fu_827_p1;
wire   [136:0] r_V_fu_831_p2;
wire   [0:0] tmp_fu_843_p3;
wire   [136:0] r_V_22_fu_837_p2;
wire   [31:0] zext_ln818_fu_851_p1;
wire   [31:0] tmp_s_fu_855_p4;
wire   [63:0] data_V_1_fu_873_p1;
wire   [51:0] p_Result_73_fu_894_p1;
wire   [53:0] mantissa_1_fu_898_p4;
wire   [10:0] xs_exp_V_1_fu_884_p4;
wire   [11:0] zext_ln515_1_fu_912_p1;
wire   [11:0] add_ln515_1_fu_916_p2;
wire   [10:0] sub_ln1512_1_fu_930_p2;
wire   [0:0] isNeg_2_fu_922_p3;
wire  signed [11:0] sext_ln1512_1_fu_936_p1;
wire   [11:0] ush_3_fu_940_p3;
wire  signed [31:0] sext_ln1488_1_fu_948_p1;
wire   [136:0] zext_ln15_1_fu_908_p1;
wire   [136:0] zext_ln1488_1_fu_952_p1;
wire   [136:0] r_V_23_fu_956_p2;
wire   [0:0] tmp_28_fu_968_p3;
wire   [136:0] r_V_24_fu_962_p2;
wire   [31:0] zext_ln818_1_fu_976_p1;
wire   [31:0] tmp_2_fu_980_p4;
wire   [31:0] result_V_5_fu_1006_p2;
wire   [31:0] result_V_8_fu_1017_p2;
wire   [31:0] add_ln180_fu_1055_p2;
wire   [31:0] sub_ln153_fu_1086_p2;
wire   [0:0] icmp_ln255_fu_1107_p2;
wire   [4:0] trunc_ln256_fu_1117_p1;
wire   [0:0] abscond_fu_1159_p2;
wire   [5:0] neg_fu_1153_p2;
wire   [5:0] abs_fu_1165_p3;
wire  signed [6:0] sext_ln288_fu_1173_p1;
wire   [0:0] tmp_30_fu_1190_p3;
wire  signed [31:0] sext_ln288_1_fu_1187_p1;
wire   [0:0] p_Repl2_5_fu_1198_p2;
wire   [4:0] add_ln368_fu_1221_p2;
wire   [31:0] zext_ln368_4_fu_1226_p1;
wire   [31:0] shl_ln368_4_fu_1230_p2;
reg   [31:0] p_Result_74_fu_1204_p4;
wire   [31:0] xor_ln368_fu_1236_p2;
wire   [31:0] zext_ln368_5_fu_1248_p1;
wire   [31:0] and_ln368_1_fu_1242_p2;
wire   [31:0] shl_ln368_5_fu_1252_p2;
reg    grp_fu_417_ce;
reg    grp_fu_425_ce;
reg    grp_fu_435_ce;
reg    ap_block_state4_on_subcall_done;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
reg    grp_fu_438_ce;
wire   [63:0] grp_fu_1675_p1;
reg   [31:0] grp_fu_1675_p0;
reg    grp_fu_1675_ce;
reg   [47:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
reg    ap_block_state2_on_subcall_done;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
reg    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
reg    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
reg    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
reg    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
reg    ap_ST_fsm_state39_blk;
reg    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
reg    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
reg    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
reg    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
reg    ap_ST_fsm_state48_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 48'd1;
#0 grp_decoder_Pipeline_decoder_label0_fu_293_ap_start_reg = 1'b0;
#0 grp_decoder_Pipeline_decoder_label1_fu_301_ap_start_reg = 1'b0;
#0 grp_decoder_Pipeline_decoder_label2_fu_309_ap_start_reg = 1'b0;
#0 grp_decoder_Pipeline_decoder_label4_fu_321_ap_start_reg = 1'b0;
#0 grp_decoder_Pipeline_decoder_label3_fu_329_ap_start_reg = 1'b0;
#0 grp_decoder_Pipeline_decoder_label9_fu_341_ap_start_reg = 1'b0;
#0 grp_decoder_Pipeline_decoder_label7_fu_349_ap_start_reg = 1'b0;
#0 grp_decoder_Pipeline_decoder_label8_fu_356_ap_start_reg = 1'b0;
#0 grp_decoder_Pipeline_decoder_label10_fu_364_ap_start_reg = 1'b0;
#0 grp_decoder_Pipeline_decoder_label5_fu_374_ap_start_reg = 1'b0;
#0 grp_decoder_Pipeline_decoder_label6_fu_381_ap_start_reg = 1'b0;
#0 grp_decoder_Pipeline_decoder_label12_fu_389_ap_start_reg = 1'b0;
#0 grp_decoder_Pipeline_decoder_label11_fu_395_ap_start_reg = 1'b0;
#0 grp_decoder_Pipeline_decoder_label14_fu_401_ap_start_reg = 1'b0;
#0 grp_decoder_Pipeline_decoder_label13_fu_409_ap_start_reg = 1'b0;
end

decoder_decoder_Pipeline_decoder_label0 grp_decoder_Pipeline_decoder_label0_fu_293(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_decoder_Pipeline_decoder_label0_fu_293_ap_start),
    .ap_done(grp_decoder_Pipeline_decoder_label0_fu_293_ap_done),
    .ap_idle(grp_decoder_Pipeline_decoder_label0_fu_293_ap_idle),
    .ap_ready(grp_decoder_Pipeline_decoder_label0_fu_293_ap_ready),
    .num1_cast(empty_51_reg_1429),
    .p_Result_14(p_Result_s_reg_1434),
    .cnt1_out(grp_decoder_Pipeline_decoder_label0_fu_293_cnt1_out),
    .cnt1_out_ap_vld(grp_decoder_Pipeline_decoder_label0_fu_293_cnt1_out_ap_vld),
    .in_1_out(grp_decoder_Pipeline_decoder_label0_fu_293_in_1_out),
    .in_1_out_ap_vld(grp_decoder_Pipeline_decoder_label0_fu_293_in_1_out_ap_vld),
    .ap_return(grp_decoder_Pipeline_decoder_label0_fu_293_ap_return)
);

decoder_decoder_Pipeline_decoder_label1 grp_decoder_Pipeline_decoder_label1_fu_301(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_decoder_Pipeline_decoder_label1_fu_301_ap_start),
    .ap_done(grp_decoder_Pipeline_decoder_label1_fu_301_ap_done),
    .ap_idle(grp_decoder_Pipeline_decoder_label1_fu_301_ap_idle),
    .ap_ready(grp_decoder_Pipeline_decoder_label1_fu_301_ap_ready),
    .num2_cast(empty_reg_1424),
    .p_Result_18(p_Result_55_reg_1440),
    .cnt2_out(grp_decoder_Pipeline_decoder_label1_fu_301_cnt2_out),
    .cnt2_out_ap_vld(grp_decoder_Pipeline_decoder_label1_fu_301_cnt2_out_ap_vld),
    .in_2_out(grp_decoder_Pipeline_decoder_label1_fu_301_in_2_out),
    .in_2_out_ap_vld(grp_decoder_Pipeline_decoder_label1_fu_301_in_2_out_ap_vld),
    .ap_return(grp_decoder_Pipeline_decoder_label1_fu_301_ap_return)
);

decoder_decoder_Pipeline_decoder_label2 grp_decoder_Pipeline_decoder_label2_fu_309(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_decoder_Pipeline_decoder_label2_fu_309_ap_start),
    .ap_done(grp_decoder_Pipeline_decoder_label2_fu_309_ap_done),
    .ap_idle(grp_decoder_Pipeline_decoder_label2_fu_309_ap_idle),
    .ap_ready(grp_decoder_Pipeline_decoder_label2_fu_309_ap_ready),
    .expo1_V(expo1_V_reg_1463),
    .exponent1_out(grp_decoder_Pipeline_decoder_label2_fu_309_exponent1_out),
    .exponent1_out_ap_vld(grp_decoder_Pipeline_decoder_label2_fu_309_exponent1_out_ap_vld),
    .grp_fu_417_p_din0(grp_decoder_Pipeline_decoder_label2_fu_309_grp_fu_417_p_din0),
    .grp_fu_417_p_din1(grp_decoder_Pipeline_decoder_label2_fu_309_grp_fu_417_p_din1),
    .grp_fu_417_p_opcode(grp_decoder_Pipeline_decoder_label2_fu_309_grp_fu_417_p_opcode),
    .grp_fu_417_p_dout0(grp_fu_417_p2),
    .grp_fu_417_p_ce(grp_decoder_Pipeline_decoder_label2_fu_309_grp_fu_417_p_ce),
    .grp_fu_425_p_din0(grp_decoder_Pipeline_decoder_label2_fu_309_grp_fu_425_p_din0),
    .grp_fu_425_p_din1(grp_decoder_Pipeline_decoder_label2_fu_309_grp_fu_425_p_din1),
    .grp_fu_425_p_dout0(grp_fu_425_p2),
    .grp_fu_425_p_ce(grp_decoder_Pipeline_decoder_label2_fu_309_grp_fu_425_p_ce),
    .grp_fu_1675_p_din0(grp_decoder_Pipeline_decoder_label2_fu_309_grp_fu_1675_p_din0),
    .grp_fu_1675_p_dout0(grp_fu_1675_p1),
    .grp_fu_1675_p_ce(grp_decoder_Pipeline_decoder_label2_fu_309_grp_fu_1675_p_ce),
    .grp_pow_generic_double_s_fu_1678_p_din1(grp_decoder_Pipeline_decoder_label2_fu_309_grp_pow_generic_double_s_fu_1678_p_din1),
    .grp_pow_generic_double_s_fu_1678_p_dout0(grp_pow_generic_double_s_fu_1678_ap_return),
    .grp_pow_generic_double_s_fu_1678_p_start(grp_decoder_Pipeline_decoder_label2_fu_309_grp_pow_generic_double_s_fu_1678_p_start),
    .grp_pow_generic_double_s_fu_1678_p_ready(grp_pow_generic_double_s_fu_1678_ap_ready),
    .grp_pow_generic_double_s_fu_1678_p_done(grp_pow_generic_double_s_fu_1678_ap_done),
    .grp_pow_generic_double_s_fu_1678_p_idle(grp_pow_generic_double_s_fu_1678_ap_idle)
);

decoder_decoder_Pipeline_decoder_label4 grp_decoder_Pipeline_decoder_label4_fu_321(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_decoder_Pipeline_decoder_label4_fu_321_ap_start),
    .ap_done(grp_decoder_Pipeline_decoder_label4_fu_321_ap_done),
    .ap_idle(grp_decoder_Pipeline_decoder_label4_fu_321_ap_idle),
    .ap_ready(grp_decoder_Pipeline_decoder_label4_fu_321_ap_ready),
    .p_Result_68(p_Result_67_reg_1470),
    .p_Result_70(p_Result_69_reg_1482),
    .mant2_new_V_1_out(grp_decoder_Pipeline_decoder_label4_fu_321_mant2_new_V_1_out),
    .mant2_new_V_1_out_ap_vld(grp_decoder_Pipeline_decoder_label4_fu_321_mant2_new_V_1_out_ap_vld),
    .mant1_new_V_1_out(grp_decoder_Pipeline_decoder_label4_fu_321_mant1_new_V_1_out),
    .mant1_new_V_1_out_ap_vld(grp_decoder_Pipeline_decoder_label4_fu_321_mant1_new_V_1_out_ap_vld)
);

decoder_decoder_Pipeline_decoder_label3 grp_decoder_Pipeline_decoder_label3_fu_329(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_decoder_Pipeline_decoder_label3_fu_329_ap_start),
    .ap_done(grp_decoder_Pipeline_decoder_label3_fu_329_ap_done),
    .ap_idle(grp_decoder_Pipeline_decoder_label3_fu_329_ap_idle),
    .ap_ready(grp_decoder_Pipeline_decoder_label3_fu_329_ap_ready),
    .expo2_V(expo2_V_reg_1475),
    .exponent2_out(grp_decoder_Pipeline_decoder_label3_fu_329_exponent2_out),
    .exponent2_out_ap_vld(grp_decoder_Pipeline_decoder_label3_fu_329_exponent2_out_ap_vld),
    .grp_fu_417_p_din0(grp_decoder_Pipeline_decoder_label3_fu_329_grp_fu_417_p_din0),
    .grp_fu_417_p_din1(grp_decoder_Pipeline_decoder_label3_fu_329_grp_fu_417_p_din1),
    .grp_fu_417_p_opcode(grp_decoder_Pipeline_decoder_label3_fu_329_grp_fu_417_p_opcode),
    .grp_fu_417_p_dout0(grp_fu_417_p2),
    .grp_fu_417_p_ce(grp_decoder_Pipeline_decoder_label3_fu_329_grp_fu_417_p_ce),
    .grp_fu_425_p_din0(grp_decoder_Pipeline_decoder_label3_fu_329_grp_fu_425_p_din0),
    .grp_fu_425_p_din1(grp_decoder_Pipeline_decoder_label3_fu_329_grp_fu_425_p_din1),
    .grp_fu_425_p_dout0(grp_fu_425_p2),
    .grp_fu_425_p_ce(grp_decoder_Pipeline_decoder_label3_fu_329_grp_fu_425_p_ce),
    .grp_fu_1675_p_din0(grp_decoder_Pipeline_decoder_label3_fu_329_grp_fu_1675_p_din0),
    .grp_fu_1675_p_dout0(grp_fu_1675_p1),
    .grp_fu_1675_p_ce(grp_decoder_Pipeline_decoder_label3_fu_329_grp_fu_1675_p_ce),
    .grp_pow_generic_double_s_fu_1678_p_din1(grp_decoder_Pipeline_decoder_label3_fu_329_grp_pow_generic_double_s_fu_1678_p_din1),
    .grp_pow_generic_double_s_fu_1678_p_dout0(grp_pow_generic_double_s_fu_1678_ap_return),
    .grp_pow_generic_double_s_fu_1678_p_start(grp_decoder_Pipeline_decoder_label3_fu_329_grp_pow_generic_double_s_fu_1678_p_start),
    .grp_pow_generic_double_s_fu_1678_p_ready(grp_pow_generic_double_s_fu_1678_ap_ready),
    .grp_pow_generic_double_s_fu_1678_p_done(grp_pow_generic_double_s_fu_1678_ap_done),
    .grp_pow_generic_double_s_fu_1678_p_idle(grp_pow_generic_double_s_fu_1678_ap_idle)
);

decoder_decoder_Pipeline_decoder_label9 grp_decoder_Pipeline_decoder_label9_fu_341(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_decoder_Pipeline_decoder_label9_fu_341_ap_start),
    .ap_done(grp_decoder_Pipeline_decoder_label9_fu_341_ap_done),
    .ap_idle(grp_decoder_Pipeline_decoder_label9_fu_341_ap_idle),
    .ap_ready(grp_decoder_Pipeline_decoder_label9_fu_341_ap_ready),
    .mant1_new_V_1_reload(grp_decoder_Pipeline_decoder_label4_fu_321_mant1_new_V_1_out),
    .mant2_new_V_1_reload(grp_decoder_Pipeline_decoder_label4_fu_321_mant2_new_V_1_out),
    .mant2_final_V_8_out(grp_decoder_Pipeline_decoder_label9_fu_341_mant2_final_V_8_out),
    .mant2_final_V_8_out_ap_vld(grp_decoder_Pipeline_decoder_label9_fu_341_mant2_final_V_8_out_ap_vld),
    .mant1_final_V_8_out(grp_decoder_Pipeline_decoder_label9_fu_341_mant1_final_V_8_out),
    .mant1_final_V_8_out_ap_vld(grp_decoder_Pipeline_decoder_label9_fu_341_mant1_final_V_8_out_ap_vld)
);

decoder_decoder_Pipeline_decoder_label7 grp_decoder_Pipeline_decoder_label7_fu_349(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_decoder_Pipeline_decoder_label7_fu_349_ap_start),
    .ap_done(grp_decoder_Pipeline_decoder_label7_fu_349_ap_done),
    .ap_idle(grp_decoder_Pipeline_decoder_label7_fu_349_ap_idle),
    .ap_ready(grp_decoder_Pipeline_decoder_label7_fu_349_ap_ready),
    .j_4(j_20_reg_1594),
    .mant1_new_V_1_reload(grp_decoder_Pipeline_decoder_label4_fu_321_mant1_new_V_1_out),
    .mant1_new_new_V_1_out(grp_decoder_Pipeline_decoder_label7_fu_349_mant1_new_new_V_1_out),
    .mant1_new_new_V_1_out_ap_vld(grp_decoder_Pipeline_decoder_label7_fu_349_mant1_new_new_V_1_out_ap_vld)
);

decoder_decoder_Pipeline_decoder_label8 grp_decoder_Pipeline_decoder_label8_fu_356(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_decoder_Pipeline_decoder_label8_fu_356_ap_start),
    .ap_done(grp_decoder_Pipeline_decoder_label8_fu_356_ap_done),
    .ap_idle(grp_decoder_Pipeline_decoder_label8_fu_356_ap_idle),
    .ap_ready(grp_decoder_Pipeline_decoder_label8_fu_356_ap_ready),
    .mant1_new_new_V_1_reload(grp_decoder_Pipeline_decoder_label7_fu_349_mant1_new_new_V_1_out),
    .mant2_new_V_1_reload(grp_decoder_Pipeline_decoder_label4_fu_321_mant2_new_V_1_out),
    .mant2_final_V_7_out(grp_decoder_Pipeline_decoder_label8_fu_356_mant2_final_V_7_out),
    .mant2_final_V_7_out_ap_vld(grp_decoder_Pipeline_decoder_label8_fu_356_mant2_final_V_7_out_ap_vld),
    .mant1_final_V_7_out(grp_decoder_Pipeline_decoder_label8_fu_356_mant1_final_V_7_out),
    .mant1_final_V_7_out_ap_vld(grp_decoder_Pipeline_decoder_label8_fu_356_mant1_final_V_7_out_ap_vld)
);

decoder_decoder_Pipeline_decoder_label10 grp_decoder_Pipeline_decoder_label10_fu_364(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_decoder_Pipeline_decoder_label10_fu_364_ap_start),
    .ap_done(grp_decoder_Pipeline_decoder_label10_fu_364_ap_done),
    .ap_idle(grp_decoder_Pipeline_decoder_label10_fu_364_ap_idle),
    .ap_ready(grp_decoder_Pipeline_decoder_label10_fu_364_ap_ready),
    .mant1_final_V_9(mant1_final_V_reg_230),
    .mant2_final_V_9(mant2_final_V_reg_242),
    .sum_V_2_out(grp_decoder_Pipeline_decoder_label10_fu_364_sum_V_2_out),
    .sum_V_2_out_ap_vld(grp_decoder_Pipeline_decoder_label10_fu_364_sum_V_2_out_ap_vld),
    .carry_V_1_out(grp_decoder_Pipeline_decoder_label10_fu_364_carry_V_1_out),
    .carry_V_1_out_ap_vld(grp_decoder_Pipeline_decoder_label10_fu_364_carry_V_1_out_ap_vld)
);

decoder_decoder_Pipeline_decoder_label5 grp_decoder_Pipeline_decoder_label5_fu_374(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_decoder_Pipeline_decoder_label5_fu_374_ap_start),
    .ap_done(grp_decoder_Pipeline_decoder_label5_fu_374_ap_done),
    .ap_idle(grp_decoder_Pipeline_decoder_label5_fu_374_ap_idle),
    .ap_ready(grp_decoder_Pipeline_decoder_label5_fu_374_ap_ready),
    .j_2(j_reg_1602),
    .mant2_new_V_1_reload(grp_decoder_Pipeline_decoder_label4_fu_321_mant2_new_V_1_out),
    .mant2_new_new_V_1_out(grp_decoder_Pipeline_decoder_label5_fu_374_mant2_new_new_V_1_out),
    .mant2_new_new_V_1_out_ap_vld(grp_decoder_Pipeline_decoder_label5_fu_374_mant2_new_new_V_1_out_ap_vld)
);

decoder_decoder_Pipeline_decoder_label6 grp_decoder_Pipeline_decoder_label6_fu_381(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_decoder_Pipeline_decoder_label6_fu_381_ap_start),
    .ap_done(grp_decoder_Pipeline_decoder_label6_fu_381_ap_done),
    .ap_idle(grp_decoder_Pipeline_decoder_label6_fu_381_ap_idle),
    .ap_ready(grp_decoder_Pipeline_decoder_label6_fu_381_ap_ready),
    .mant1_new_V_1_reload(grp_decoder_Pipeline_decoder_label4_fu_321_mant1_new_V_1_out),
    .mant2_new_new_V_1_reload(grp_decoder_Pipeline_decoder_label5_fu_374_mant2_new_new_V_1_out),
    .mant2_final_V_out(grp_decoder_Pipeline_decoder_label6_fu_381_mant2_final_V_out),
    .mant2_final_V_out_ap_vld(grp_decoder_Pipeline_decoder_label6_fu_381_mant2_final_V_out_ap_vld),
    .mant1_final_V_out(grp_decoder_Pipeline_decoder_label6_fu_381_mant1_final_V_out),
    .mant1_final_V_out_ap_vld(grp_decoder_Pipeline_decoder_label6_fu_381_mant1_final_V_out_ap_vld)
);

decoder_decoder_Pipeline_decoder_label12 grp_decoder_Pipeline_decoder_label12_fu_389(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_decoder_Pipeline_decoder_label12_fu_389_ap_start),
    .ap_done(grp_decoder_Pipeline_decoder_label12_fu_389_ap_done),
    .ap_idle(grp_decoder_Pipeline_decoder_label12_fu_389_ap_idle),
    .ap_ready(grp_decoder_Pipeline_decoder_label12_fu_389_ap_ready),
    .k_final_1(trunc_ln256_1_reg_1631),
    .result_V_26_out(grp_decoder_Pipeline_decoder_label12_fu_389_result_V_26_out),
    .result_V_26_out_ap_vld(grp_decoder_Pipeline_decoder_label12_fu_389_result_V_26_out_ap_vld)
);

decoder_decoder_Pipeline_decoder_label11 grp_decoder_Pipeline_decoder_label11_fu_395(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_decoder_Pipeline_decoder_label11_fu_395_ap_start),
    .ap_done(grp_decoder_Pipeline_decoder_label11_fu_395_ap_done),
    .ap_idle(grp_decoder_Pipeline_decoder_label11_fu_395_ap_idle),
    .ap_ready(grp_decoder_Pipeline_decoder_label11_fu_395_ap_ready),
    .sub228(sub228_reg_1636),
    .result_V_25_out(grp_decoder_Pipeline_decoder_label11_fu_395_result_V_25_out),
    .result_V_25_out_ap_vld(grp_decoder_Pipeline_decoder_label11_fu_395_result_V_25_out_ap_vld)
);

decoder_decoder_Pipeline_decoder_label14 grp_decoder_Pipeline_decoder_label14_fu_401(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_decoder_Pipeline_decoder_label14_fu_401_ap_start),
    .ap_done(grp_decoder_Pipeline_decoder_label14_fu_401_ap_done),
    .ap_idle(grp_decoder_Pipeline_decoder_label14_fu_401_ap_idle),
    .ap_ready(grp_decoder_Pipeline_decoder_label14_fu_401_ap_ready),
    .p_Result_95(p_Result_75_reg_1664),
    .sext_ln303(j_22_reg_1658),
    .r_V_28(r_V_26_reg_1670),
    .result_V_29_out(grp_decoder_Pipeline_decoder_label14_fu_401_result_V_29_out),
    .result_V_29_out_ap_vld(grp_decoder_Pipeline_decoder_label14_fu_401_result_V_29_out_ap_vld)
);

decoder_decoder_Pipeline_decoder_label13 grp_decoder_Pipeline_decoder_label13_fu_409(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_decoder_Pipeline_decoder_label13_fu_409_ap_start),
    .ap_done(grp_decoder_Pipeline_decoder_label13_fu_409_ap_done),
    .ap_idle(grp_decoder_Pipeline_decoder_label13_fu_409_ap_idle),
    .ap_ready(grp_decoder_Pipeline_decoder_label13_fu_409_ap_ready),
    .p_Result_95(p_Result_75_reg_1664),
    .sext_ln303(j_22_reg_1658),
    .sum_V_2_reload(grp_decoder_Pipeline_decoder_label10_fu_364_sum_V_2_out),
    .result_V_28_out(grp_decoder_Pipeline_decoder_label13_fu_409_result_V_28_out),
    .result_V_28_out_ap_vld(grp_decoder_Pipeline_decoder_label13_fu_409_result_V_28_out_ap_vld)
);

decoder_pow_generic_double_s grp_pow_generic_double_s_fu_1678(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_pow_generic_double_s_fu_1678_ap_start),
    .ap_done(grp_pow_generic_double_s_fu_1678_ap_done),
    .ap_idle(grp_pow_generic_double_s_fu_1678_ap_idle),
    .ap_ready(grp_pow_generic_double_s_fu_1678_ap_ready),
    .exp(grp_pow_generic_double_s_fu_1678_exp),
    .ap_return(grp_pow_generic_double_s_fu_1678_ap_return)
);

decoder_dadd_64ns_64ns_64_8_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_8_full_dsp_1_U73(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_417_p0),
    .din1(grp_fu_417_p1),
    .ce(grp_fu_417_ce),
    .dout(grp_fu_417_p2)
);

decoder_dadd_64ns_64ns_64_8_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dadd_64ns_64ns_64_8_full_dsp_1_U74(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul3_reg_1515),
    .din1(reg_447),
    .ce(1'b1),
    .dout(grp_fu_421_p2)
);

decoder_dmul_64ns_64ns_64_7_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_7_max_dsp_1_U75(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_425_p0),
    .din1(grp_fu_425_p1),
    .ce(grp_fu_425_ce),
    .dout(grp_fu_425_p2)
);

decoder_dmul_64ns_64ns_64_7_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_7_max_dsp_1_U76(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_447),
    .din1(64'd4616189618054758400),
    .ce(1'b1),
    .dout(grp_fu_430_p2)
);

decoder_sitodp_32s_64_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
sitodp_32s_64_6_no_dsp_1_U77(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_435_p0),
    .ce(grp_fu_435_ce),
    .dout(grp_fu_435_p1)
);

decoder_sitodp_32s_64_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
sitodp_32s_64_6_no_dsp_1_U78(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_438_p0),
    .ce(grp_fu_438_ce),
    .dout(grp_fu_438_p1)
);

decoder_sitodp_32ns_64_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
sitodp_32ns_64_6_no_dsp_1_U79(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1675_p0),
    .ce(grp_fu_1675_ce),
    .dout(grp_fu_1675_p1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_decoder_Pipeline_decoder_label0_fu_293_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            grp_decoder_Pipeline_decoder_label0_fu_293_ap_start_reg <= 1'b1;
        end else if ((grp_decoder_Pipeline_decoder_label0_fu_293_ap_ready == 1'b1)) begin
            grp_decoder_Pipeline_decoder_label0_fu_293_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_decoder_Pipeline_decoder_label10_fu_364_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state35)) begin
            grp_decoder_Pipeline_decoder_label10_fu_364_ap_start_reg <= 1'b1;
        end else if ((grp_decoder_Pipeline_decoder_label10_fu_364_ap_ready == 1'b1)) begin
            grp_decoder_Pipeline_decoder_label10_fu_364_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_decoder_Pipeline_decoder_label11_fu_395_ap_start_reg <= 1'b0;
    end else begin
        if (((tmp_29_fu_1121_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state41))) begin
            grp_decoder_Pipeline_decoder_label11_fu_395_ap_start_reg <= 1'b1;
        end else if ((grp_decoder_Pipeline_decoder_label11_fu_395_ap_ready == 1'b1)) begin
            grp_decoder_Pipeline_decoder_label11_fu_395_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_decoder_Pipeline_decoder_label12_fu_389_ap_start_reg <= 1'b0;
    end else begin
        if (((tmp_29_fu_1121_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state41))) begin
            grp_decoder_Pipeline_decoder_label12_fu_389_ap_start_reg <= 1'b1;
        end else if ((grp_decoder_Pipeline_decoder_label12_fu_389_ap_ready == 1'b1)) begin
            grp_decoder_Pipeline_decoder_label12_fu_389_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_decoder_Pipeline_decoder_label13_fu_409_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state45) & (carry_V_1_loc_load_reg_1613 == 1'd1))) begin
            grp_decoder_Pipeline_decoder_label13_fu_409_ap_start_reg <= 1'b1;
        end else if ((grp_decoder_Pipeline_decoder_label13_fu_409_ap_ready == 1'b1)) begin
            grp_decoder_Pipeline_decoder_label13_fu_409_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_decoder_Pipeline_decoder_label14_fu_401_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state45) & (carry_V_1_loc_load_reg_1613 == 1'd0))) begin
            grp_decoder_Pipeline_decoder_label14_fu_401_ap_start_reg <= 1'b1;
        end else if ((grp_decoder_Pipeline_decoder_label14_fu_401_ap_ready == 1'b1)) begin
            grp_decoder_Pipeline_decoder_label14_fu_401_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_decoder_Pipeline_decoder_label1_fu_301_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            grp_decoder_Pipeline_decoder_label1_fu_301_ap_start_reg <= 1'b1;
        end else if ((grp_decoder_Pipeline_decoder_label1_fu_301_ap_ready == 1'b1)) begin
            grp_decoder_Pipeline_decoder_label1_fu_301_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_decoder_Pipeline_decoder_label2_fu_309_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_decoder_Pipeline_decoder_label2_fu_309_ap_start_reg <= 1'b1;
        end else if ((grp_decoder_Pipeline_decoder_label2_fu_309_ap_ready == 1'b1)) begin
            grp_decoder_Pipeline_decoder_label2_fu_309_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_decoder_Pipeline_decoder_label3_fu_329_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_decoder_Pipeline_decoder_label3_fu_329_ap_start_reg <= 1'b1;
        end else if ((grp_decoder_Pipeline_decoder_label3_fu_329_ap_ready == 1'b1)) begin
            grp_decoder_Pipeline_decoder_label3_fu_329_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_decoder_Pipeline_decoder_label4_fu_321_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_decoder_Pipeline_decoder_label4_fu_321_ap_start_reg <= 1'b1;
        end else if ((grp_decoder_Pipeline_decoder_label4_fu_321_ap_ready == 1'b1)) begin
            grp_decoder_Pipeline_decoder_label4_fu_321_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_decoder_Pipeline_decoder_label5_fu_374_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state36)) begin
            grp_decoder_Pipeline_decoder_label5_fu_374_ap_start_reg <= 1'b1;
        end else if ((grp_decoder_Pipeline_decoder_label5_fu_374_ap_ready == 1'b1)) begin
            grp_decoder_Pipeline_decoder_label5_fu_374_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_decoder_Pipeline_decoder_label6_fu_381_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state38)) begin
            grp_decoder_Pipeline_decoder_label6_fu_381_ap_start_reg <= 1'b1;
        end else if ((grp_decoder_Pipeline_decoder_label6_fu_381_ap_ready == 1'b1)) begin
            grp_decoder_Pipeline_decoder_label6_fu_381_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_decoder_Pipeline_decoder_label7_fu_349_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state31)) begin
            grp_decoder_Pipeline_decoder_label7_fu_349_ap_start_reg <= 1'b1;
        end else if ((grp_decoder_Pipeline_decoder_label7_fu_349_ap_ready == 1'b1)) begin
            grp_decoder_Pipeline_decoder_label7_fu_349_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_decoder_Pipeline_decoder_label8_fu_356_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state33)) begin
            grp_decoder_Pipeline_decoder_label8_fu_356_ap_start_reg <= 1'b1;
        end else if ((grp_decoder_Pipeline_decoder_label8_fu_356_ap_ready == 1'b1)) begin
            grp_decoder_Pipeline_decoder_label8_fu_356_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_decoder_Pipeline_decoder_label9_fu_341_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state26) & (icmp_ln175_fu_1034_p2 == 1'd0) & (icmp_ln147_fu_1028_p2 == 1'd0))) begin
            grp_decoder_Pipeline_decoder_label9_fu_341_ap_start_reg <= 1'b1;
        end else if ((grp_decoder_Pipeline_decoder_label9_fu_341_ap_ready == 1'b1)) begin
            grp_decoder_Pipeline_decoder_label9_fu_341_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state35) & (icmp_ln147_reg_1570 == 1'd1))) begin
        exponent_arr_V_2_reg_254 <= expo1_V_reg_1463;
    end else if (((1'b1 == ap_CS_fsm_state35) & (icmp_ln175_reg_1574 == 1'd1) & (icmp_ln147_reg_1570 == 1'd0))) begin
        exponent_arr_V_2_reg_254 <= expo2_V_reg_1475;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        exponent_arr_V_2_reg_254 <= exponent_arr_V_1_fu_1050_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state35) & (icmp_ln147_reg_1570 == 1'd1))) begin
        mant1_final_V_reg_230 <= grp_decoder_Pipeline_decoder_label6_fu_381_mant1_final_V_out;
    end else if (((1'b1 == ap_CS_fsm_state35) & (icmp_ln175_reg_1574 == 1'd1) & (icmp_ln147_reg_1570 == 1'd0))) begin
        mant1_final_V_reg_230 <= grp_decoder_Pipeline_decoder_label8_fu_356_mant1_final_V_7_out;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        mant1_final_V_reg_230 <= grp_decoder_Pipeline_decoder_label9_fu_341_mant1_final_V_8_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state35) & (icmp_ln147_reg_1570 == 1'd1))) begin
        mant2_final_V_reg_242 <= grp_decoder_Pipeline_decoder_label6_fu_381_mant2_final_V_out;
    end else if (((1'b1 == ap_CS_fsm_state35) & (icmp_ln175_reg_1574 == 1'd1) & (icmp_ln147_reg_1570 == 1'd0))) begin
        mant2_final_V_reg_242 <= grp_decoder_Pipeline_decoder_label8_fu_356_mant2_final_V_7_out;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        mant2_final_V_reg_242 <= grp_decoder_Pipeline_decoder_label9_fu_341_mant2_final_V_8_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        if ((tmp_29_reg_1622 == 1'd1)) begin
            result_V_reg_275 <= grp_decoder_Pipeline_decoder_label11_fu_395_result_V_25_out;
        end else if ((tmp_29_reg_1622 == 1'd0)) begin
            result_V_reg_275 <= grp_decoder_Pipeline_decoder_label12_fu_389_result_V_26_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        carry_V_1_loc_load_reg_1613 <= grp_decoder_Pipeline_decoder_label10_fu_364_carry_V_1_out;
        k_final_reg_1617 <= k_final_fu_1111_p3;
        tmp_29_reg_1622 <= k_final_fu_1111_p3[32'd5];
    end
end

always @ (posedge ap_clk) begin
    if (((grp_decoder_Pipeline_decoder_label0_fu_293_cnt1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        cnt1_loc_fu_214 <= grp_decoder_Pipeline_decoder_label0_fu_293_cnt1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_decoder_Pipeline_decoder_label1_fu_301_cnt2_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        cnt2_loc_fu_206 <= grp_decoder_Pipeline_decoder_label1_fu_301_cnt2_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        dc_1_reg_1525 <= grp_fu_421_p2;
        dc_reg_1520 <= grp_fu_417_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        empty_51_reg_1429 <= empty_51_fu_458_p1;
        empty_reg_1424 <= empty_fu_453_p1;
        p_Result_55_reg_1440 <= num2[32'd30];
        p_Result_s_reg_1434 <= num1[32'd30];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        exp1_conv_reg_1558 <= exp1_conv_fu_1011_p3;
        exp2_conv_reg_1564 <= exp2_conv_fu_1022_p3;
        icmp_ln147_reg_1570 <= icmp_ln147_fu_1028_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        expo1_V_reg_1463 <= expo1_V_fu_540_p1;
        expo2_V_reg_1475 <= expo2_V_fu_647_p1;
        k1_2_reg_1456 <= k1_2_fu_514_p3;
        k2_4_reg_1487 <= k2_4_fu_725_p3;
        p_Result_67_reg_1470 <= p_Result_67_fu_600_p2;
        p_Result_69_reg_1482 <= p_Result_69_fu_706_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state26) & (icmp_ln147_fu_1028_p2 == 1'd0))) begin
        icmp_ln175_reg_1574 <= icmp_ln175_fu_1034_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state26) & (icmp_ln175_fu_1034_p2 == 1'd0) & (icmp_ln147_fu_1028_p2 == 1'd0))) begin
        icmp_ln216_reg_1578 <= icmp_ln216_fu_1040_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_decoder_Pipeline_decoder_label0_fu_293_in_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        in_1_loc_fu_210 <= grp_decoder_Pipeline_decoder_label0_fu_293_in_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_decoder_Pipeline_decoder_label1_fu_301_in_2_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        in_2_loc_fu_202 <= grp_decoder_Pipeline_decoder_label1_fu_301_in_2_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        j_20_reg_1594 <= j_20_fu_1060_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        j_22_reg_1658 <= j_22_fu_1214_p2;
        p_Result_75_reg_1664 <= p_Result_75_fu_1258_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        j_reg_1602 <= j_fu_1091_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_29_fu_1121_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state41))) begin
        k_final_1_reg_1626 <= k_final_1_fu_1129_p2;
        trunc_ln256_1_reg_1631 <= trunc_ln256_1_fu_1135_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        mul2_reg_1510 <= grp_fu_425_p2;
        mul3_reg_1515 <= grp_fu_430_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        opposite_bit_index_final_reg_1647 <= opposite_bit_index_final_fu_1177_p2;
        trunc_ln297_reg_1653 <= trunc_ln297_fu_1183_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        p_Result_70_reg_1530 <= data_V_fu_748_p1[32'd63];
        p_Result_72_reg_1541 <= data_V_1_fu_873_p1[32'd63];
        val_1_reg_1546 <= val_1_fu_990_p3;
        val_reg_1535 <= val_fu_865_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state45) & (carry_V_1_loc_load_reg_1613 == 1'd0))) begin
        r_V_26_reg_1670[28 : 1] <= r_V_26_fu_1266_p2[28 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state9))) begin
        reg_441 <= grp_fu_435_p1;
        reg_447 <= grp_fu_438_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_29_fu_1121_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state41))) begin
        sub228_reg_1636 <= sub228_fu_1140_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        targetBlock8_reg_1451 <= grp_decoder_Pipeline_decoder_label1_fu_301_ap_return;
        targetBlock_reg_1446 <= grp_decoder_Pipeline_decoder_label0_fu_293_ap_return;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

always @ (*) begin
    if ((grp_decoder_Pipeline_decoder_label9_fu_341_ap_done == 1'b0)) begin
        ap_ST_fsm_state27_blk = 1'b1;
    end else begin
        ap_ST_fsm_state27_blk = 1'b0;
    end
end

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

always @ (*) begin
    if ((grp_decoder_Pipeline_decoder_label7_fu_349_ap_done == 1'b0)) begin
        ap_ST_fsm_state32_blk = 1'b1;
    end else begin
        ap_ST_fsm_state32_blk = 1'b0;
    end
end

assign ap_ST_fsm_state33_blk = 1'b0;

always @ (*) begin
    if ((grp_decoder_Pipeline_decoder_label8_fu_356_ap_done == 1'b0)) begin
        ap_ST_fsm_state34_blk = 1'b1;
    end else begin
        ap_ST_fsm_state34_blk = 1'b0;
    end
end

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

always @ (*) begin
    if ((grp_decoder_Pipeline_decoder_label5_fu_374_ap_done == 1'b0)) begin
        ap_ST_fsm_state37_blk = 1'b1;
    end else begin
        ap_ST_fsm_state37_blk = 1'b0;
    end
end

assign ap_ST_fsm_state38_blk = 1'b0;

always @ (*) begin
    if ((grp_decoder_Pipeline_decoder_label6_fu_381_ap_done == 1'b0)) begin
        ap_ST_fsm_state39_blk = 1'b1;
    end else begin
        ap_ST_fsm_state39_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_decoder_Pipeline_decoder_label10_fu_364_ap_done == 1'b0)) begin
        ap_ST_fsm_state40_blk = 1'b1;
    end else begin
        ap_ST_fsm_state40_blk = 1'b0;
    end
end

assign ap_ST_fsm_state41_blk = 1'b0;

always @ (*) begin
    if ((grp_decoder_Pipeline_decoder_label12_fu_389_ap_done == 1'b0)) begin
        ap_ST_fsm_state42_blk = 1'b1;
    end else begin
        ap_ST_fsm_state42_blk = 1'b0;
    end
end

assign ap_ST_fsm_state43_blk = 1'b0;

always @ (*) begin
    if ((grp_decoder_Pipeline_decoder_label11_fu_395_ap_done == 1'b0)) begin
        ap_ST_fsm_state44_blk = 1'b1;
    end else begin
        ap_ST_fsm_state44_blk = 1'b0;
    end
end

assign ap_ST_fsm_state45_blk = 1'b0;

always @ (*) begin
    if ((grp_decoder_Pipeline_decoder_label14_fu_401_ap_done == 1'b0)) begin
        ap_ST_fsm_state46_blk = 1'b1;
    end else begin
        ap_ST_fsm_state46_blk = 1'b0;
    end
end

assign ap_ST_fsm_state47_blk = 1'b0;

always @ (*) begin
    if ((grp_decoder_Pipeline_decoder_label13_fu_409_ap_done == 1'b0)) begin
        ap_ST_fsm_state48_blk = 1'b1;
    end else begin
        ap_ST_fsm_state48_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_decoder_Pipeline_decoder_label3_fu_329_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state43)) begin
        if ((tmp_29_reg_1622 == 1'd1)) begin
            ap_phi_mux_k_final_2_phi_fu_269_p4 = k_final_reg_1617;
        end else if ((tmp_29_reg_1622 == 1'd0)) begin
            ap_phi_mux_k_final_2_phi_fu_269_p4 = k_final_1_reg_1626;
        end else begin
            ap_phi_mux_k_final_2_phi_fu_269_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_k_final_2_phi_fu_269_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state47)) begin
        if ((carry_V_1_loc_load_reg_1613 == 1'd1)) begin
            ap_phi_mux_result_V_9_phi_fu_287_p4 = grp_decoder_Pipeline_decoder_label13_fu_409_result_V_28_out;
        end else if ((carry_V_1_loc_load_reg_1613 == 1'd0)) begin
            ap_phi_mux_result_V_9_phi_fu_287_p4 = grp_decoder_Pipeline_decoder_label14_fu_401_result_V_29_out;
        end else begin
            ap_phi_mux_result_V_9_phi_fu_287_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_result_V_9_phi_fu_287_p4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_1675_ce = grp_decoder_Pipeline_decoder_label3_fu_329_grp_fu_1675_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_1675_ce = grp_decoder_Pipeline_decoder_label2_fu_309_grp_fu_1675_p_ce;
    end else begin
        grp_fu_1675_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_1675_p0 = grp_decoder_Pipeline_decoder_label3_fu_329_grp_fu_1675_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_1675_p0 = grp_decoder_Pipeline_decoder_label2_fu_309_grp_fu_1675_p_din0;
    end else begin
        grp_fu_1675_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_417_ce = grp_decoder_Pipeline_decoder_label3_fu_329_grp_fu_417_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_417_ce = grp_decoder_Pipeline_decoder_label2_fu_309_grp_fu_417_p_ce;
    end else begin
        grp_fu_417_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_417_p0 = grp_decoder_Pipeline_decoder_label3_fu_329_grp_fu_417_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_417_p0 = grp_decoder_Pipeline_decoder_label2_fu_309_grp_fu_417_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_417_p0 = mul2_reg_1510;
    end else begin
        grp_fu_417_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_417_p1 = grp_decoder_Pipeline_decoder_label3_fu_329_grp_fu_417_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_417_p1 = grp_decoder_Pipeline_decoder_label2_fu_309_grp_fu_417_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_417_p1 = reg_441;
    end else begin
        grp_fu_417_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_425_ce = grp_decoder_Pipeline_decoder_label3_fu_329_grp_fu_425_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_425_ce = grp_decoder_Pipeline_decoder_label2_fu_309_grp_fu_425_p_ce;
    end else begin
        grp_fu_425_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_425_p0 = grp_decoder_Pipeline_decoder_label3_fu_329_grp_fu_425_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_425_p0 = grp_decoder_Pipeline_decoder_label2_fu_309_grp_fu_425_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_425_p0 = reg_441;
    end else begin
        grp_fu_425_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_425_p1 = grp_decoder_Pipeline_decoder_label3_fu_329_grp_fu_425_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_425_p1 = grp_decoder_Pipeline_decoder_label2_fu_309_grp_fu_425_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_425_p1 = 64'd4616189618054758400;
    end else begin
        grp_fu_425_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_on_subcall_done)) | ((grp_decoder_Pipeline_decoder_label3_fu_329_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        grp_fu_435_ce = 1'b1;
    end else begin
        grp_fu_435_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_435_p0 = grp_decoder_Pipeline_decoder_label2_fu_309_exponent1_out;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_435_p0 = sext_ln125_fu_732_p1;
    end else begin
        grp_fu_435_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_on_subcall_done)) | ((grp_decoder_Pipeline_decoder_label3_fu_329_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6)))) begin
        grp_fu_438_ce = 1'b1;
    end else begin
        grp_fu_438_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_438_p0 = grp_decoder_Pipeline_decoder_label3_fu_329_exponent2_out;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_438_p0 = sext_ln126_fu_736_p1;
    end else begin
        grp_fu_438_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_pow_generic_double_s_fu_1678_ap_start = grp_decoder_Pipeline_decoder_label3_fu_329_grp_pow_generic_double_s_fu_1678_p_start;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_pow_generic_double_s_fu_1678_ap_start = grp_decoder_Pipeline_decoder_label2_fu_309_grp_pow_generic_double_s_fu_1678_p_start;
    end else begin
        grp_pow_generic_double_s_fu_1678_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_pow_generic_double_s_fu_1678_exp = grp_decoder_Pipeline_decoder_label3_fu_329_grp_pow_generic_double_s_fu_1678_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_pow_generic_double_s_fu_1678_exp = grp_decoder_Pipeline_decoder_label2_fu_309_grp_pow_generic_double_s_fu_1678_p_din1;
    end else begin
        grp_pow_generic_double_s_fu_1678_exp = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (1'b0 == ap_block_state2_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (1'b0 == ap_block_state4_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_decoder_Pipeline_decoder_label3_fu_329_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            if (((1'b1 == ap_CS_fsm_state26) & (icmp_ln175_fu_1034_p2 == 1'd1) & (icmp_ln147_fu_1028_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else if (((1'b1 == ap_CS_fsm_state26) & (icmp_ln175_fu_1034_p2 == 1'd0) & (icmp_ln147_fu_1028_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end
        end
        ap_ST_fsm_state27 : begin
            if (((grp_decoder_Pipeline_decoder_label9_fu_341_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state27))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            if (((grp_decoder_Pipeline_decoder_label7_fu_349_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state32))) begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            if (((grp_decoder_Pipeline_decoder_label8_fu_356_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state34))) begin
                ap_NS_fsm = ap_ST_fsm_state35;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            if (((grp_decoder_Pipeline_decoder_label5_fu_374_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state37))) begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state37;
            end
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            if (((grp_decoder_Pipeline_decoder_label6_fu_381_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state39))) begin
                ap_NS_fsm = ap_ST_fsm_state35;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state39;
            end
        end
        ap_ST_fsm_state40 : begin
            if (((grp_decoder_Pipeline_decoder_label10_fu_364_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state40))) begin
                ap_NS_fsm = ap_ST_fsm_state41;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state40;
            end
        end
        ap_ST_fsm_state41 : begin
            if (((tmp_29_fu_1121_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state41))) begin
                ap_NS_fsm = ap_ST_fsm_state44;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end
        end
        ap_ST_fsm_state42 : begin
            if (((grp_decoder_Pipeline_decoder_label12_fu_389_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state42))) begin
                ap_NS_fsm = ap_ST_fsm_state43;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state44 : begin
            if (((grp_decoder_Pipeline_decoder_label11_fu_395_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state44))) begin
                ap_NS_fsm = ap_ST_fsm_state43;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state44;
            end
        end
        ap_ST_fsm_state45 : begin
            if (((1'b1 == ap_CS_fsm_state45) & (carry_V_1_loc_load_reg_1613 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state48;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state46;
            end
        end
        ap_ST_fsm_state46 : begin
            if (((grp_decoder_Pipeline_decoder_label14_fu_401_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state46))) begin
                ap_NS_fsm = ap_ST_fsm_state47;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state46;
            end
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state48 : begin
            if (((grp_decoder_Pipeline_decoder_label13_fu_409_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state48))) begin
                ap_NS_fsm = ap_ST_fsm_state47;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state48;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign abs_fu_1165_p3 = ((abscond_fu_1159_p2[0:0] == 1'b1) ? ap_phi_mux_k_final_2_phi_fu_269_p4 : neg_fu_1153_p2);

assign abscond_fu_1159_p2 = (($signed(ap_phi_mux_k_final_2_phi_fu_269_p4) > $signed(6'd0)) ? 1'b1 : 1'b0);

assign add_ln180_fu_1055_p2 = (exp1_conv_reg_1558 + 32'd28);

assign add_ln368_fu_1221_p2 = ($signed(trunc_ln297_reg_1653) + $signed(5'd30));

assign add_ln515_1_fu_916_p2 = ($signed(zext_ln515_1_fu_912_p1) + $signed(12'd3073));

assign add_ln515_fu_791_p2 = ($signed(zext_ln515_fu_787_p1) + $signed(12'd3073));

assign add_ln628_1_fu_632_p2 = ($signed(trunc_ln98_fu_628_p1) + $signed(5'd30));

assign add_ln628_fu_525_p2 = ($signed(trunc_ln60_fu_521_p1) + $signed(5'd30));

assign and_ln368_1_fu_1242_p2 = (xor_ln368_fu_1236_p2 & p_Result_74_fu_1204_p4);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state46 = ap_CS_fsm[32'd45];

assign ap_CS_fsm_state47 = ap_CS_fsm[32'd46];

assign ap_CS_fsm_state48 = ap_CS_fsm[32'd47];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_decoder_Pipeline_decoder_label1_fu_301_ap_done == 1'b0) | (grp_decoder_Pipeline_decoder_label0_fu_293_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state4_on_subcall_done = ((grp_decoder_Pipeline_decoder_label4_fu_321_ap_done == 1'b0) | (grp_decoder_Pipeline_decoder_label2_fu_309_ap_done == 1'b0));
end

assign ap_return = ap_phi_mux_result_V_9_phi_fu_287_p4;

assign cnt1_cast_fu_494_p1 = cnt1_loc_fu_214;

assign cnt2_cast_fu_620_p1 = cnt2_loc_fu_206;

assign data_V_1_fu_873_p1 = dc_1_reg_1525;

assign data_V_fu_748_p1 = dc_reg_1520;

assign empty_51_fu_458_p1 = num1[30:0];

assign empty_fu_453_p1 = num2[30:0];

assign exp1_conv_fu_1011_p3 = ((p_Result_70_reg_1530[0:0] == 1'b1) ? result_V_5_fu_1006_p2 : val_reg_1535);

assign exp2_conv_fu_1022_p3 = ((p_Result_72_reg_1541[0:0] == 1'b1) ? result_V_8_fu_1017_p2 : val_1_reg_1546);

assign expo1_V_fu_540_p1 = lshr_ln628_fu_535_p2[1:0];

assign expo2_V_fu_647_p1 = lshr_ln628_2_fu_642_p2[1:0];

assign exponent_arr_V_1_fu_1050_p3 = ((icmp_ln216_reg_1578[0:0] == 1'b1) ? expo1_V_reg_1463 : expo2_V_reg_1475);

assign grp_decoder_Pipeline_decoder_label0_fu_293_ap_start = grp_decoder_Pipeline_decoder_label0_fu_293_ap_start_reg;

assign grp_decoder_Pipeline_decoder_label10_fu_364_ap_start = grp_decoder_Pipeline_decoder_label10_fu_364_ap_start_reg;

assign grp_decoder_Pipeline_decoder_label11_fu_395_ap_start = grp_decoder_Pipeline_decoder_label11_fu_395_ap_start_reg;

assign grp_decoder_Pipeline_decoder_label12_fu_389_ap_start = grp_decoder_Pipeline_decoder_label12_fu_389_ap_start_reg;

assign grp_decoder_Pipeline_decoder_label13_fu_409_ap_start = grp_decoder_Pipeline_decoder_label13_fu_409_ap_start_reg;

assign grp_decoder_Pipeline_decoder_label14_fu_401_ap_start = grp_decoder_Pipeline_decoder_label14_fu_401_ap_start_reg;

assign grp_decoder_Pipeline_decoder_label1_fu_301_ap_start = grp_decoder_Pipeline_decoder_label1_fu_301_ap_start_reg;

assign grp_decoder_Pipeline_decoder_label2_fu_309_ap_start = grp_decoder_Pipeline_decoder_label2_fu_309_ap_start_reg;

assign grp_decoder_Pipeline_decoder_label3_fu_329_ap_start = grp_decoder_Pipeline_decoder_label3_fu_329_ap_start_reg;

assign grp_decoder_Pipeline_decoder_label4_fu_321_ap_start = grp_decoder_Pipeline_decoder_label4_fu_321_ap_start_reg;

assign grp_decoder_Pipeline_decoder_label5_fu_374_ap_start = grp_decoder_Pipeline_decoder_label5_fu_374_ap_start_reg;

assign grp_decoder_Pipeline_decoder_label6_fu_381_ap_start = grp_decoder_Pipeline_decoder_label6_fu_381_ap_start_reg;

assign grp_decoder_Pipeline_decoder_label7_fu_349_ap_start = grp_decoder_Pipeline_decoder_label7_fu_349_ap_start_reg;

assign grp_decoder_Pipeline_decoder_label8_fu_356_ap_start = grp_decoder_Pipeline_decoder_label8_fu_356_ap_start_reg;

assign grp_decoder_Pipeline_decoder_label9_fu_341_ap_start = grp_decoder_Pipeline_decoder_label9_fu_341_ap_start_reg;

assign icmp_ln147_fu_1028_p2 = (($signed(exp1_conv_fu_1011_p3) > $signed(exp2_conv_fu_1022_p3)) ? 1'b1 : 1'b0);

assign icmp_ln175_fu_1034_p2 = (($signed(exp2_conv_fu_1022_p3) > $signed(exp1_conv_fu_1011_p3)) ? 1'b1 : 1'b0);

assign icmp_ln216_fu_1040_p2 = (($signed(grp_decoder_Pipeline_decoder_label2_fu_309_exponent1_out) > $signed(grp_decoder_Pipeline_decoder_label3_fu_329_exponent2_out)) ? 1'b1 : 1'b0);

assign icmp_ln255_fu_1107_p2 = (($signed(k1_2_reg_1456) > $signed(k2_4_reg_1487)) ? 1'b1 : 1'b0);

assign isNeg_2_fu_922_p3 = add_ln515_1_fu_916_p2[32'd11];

assign isNeg_fu_797_p3 = add_ln515_fu_791_p2[32'd11];

assign j_20_fu_1060_p2 = (add_ln180_fu_1055_p2 - exp2_conv_reg_1564);

assign j_22_fu_1214_p2 = ($signed(opposite_bit_index_final_reg_1647) + $signed(7'd125));

assign j_fu_1091_p2 = (sub_ln153_fu_1086_p2 + exp2_conv_reg_1564);

assign k1_1_fu_508_p2 = ($signed(cnt1_cast_fu_494_p1) + $signed(6'd63));

assign k1_2_fu_514_p3 = ((p_Result_s_reg_1434[0:0] == 1'b1) ? k1_1_fu_508_p2 : k1_fu_502_p2);

assign k1_fu_502_p2 = (6'd0 - cnt1_cast_fu_494_p1);

assign k2_3_fu_713_p2 = ($signed(cnt2_cast_fu_620_p1) + $signed(6'd63));

assign k2_4_fu_725_p3 = ((p_Result_55_reg_1440[0:0] == 1'b1) ? k2_3_fu_713_p2 : k2_fu_719_p2);

assign k2_fu_719_p2 = (6'd0 - cnt2_cast_fu_620_p1);

assign k_final_1_fu_1129_p2 = (k_final_fu_1111_p3 + 6'd1);

assign k_final_fu_1111_p3 = ((icmp_ln255_fu_1107_p2[0:0] == 1'b1) ? k1_2_reg_1456 : k2_4_reg_1487);

assign lshr_ln628_1_fu_565_p2 = 32'd4294967295 >> zext_ln628_1_fu_561_p1;

assign lshr_ln628_2_fu_642_p2 = num2 >> zext_ln628_2_fu_638_p1;

assign lshr_ln628_3_fu_665_p2 = 32'd4294967295 >> zext_ln628_3_fu_661_p1;

assign lshr_ln628_fu_535_p2 = num1 >> zext_ln628_fu_531_p1;

assign mantissa_1_fu_898_p4 = {{{{1'd1}, {p_Result_73_fu_894_p1}}}, {1'd0}};

assign mantissa_fu_773_p4 = {{{{1'd1}, {p_Result_71_fu_769_p1}}}, {1'd0}};

assign neg_fu_1153_p2 = (6'd0 - ap_phi_mux_k_final_2_phi_fu_269_p4);

assign opposite_bit_index_final_fu_1177_p2 = ($signed(7'd30) - $signed(sext_ln288_fu_1173_p1));

assign p_Repl2_5_fu_1198_p2 = (tmp_30_fu_1190_p3 ^ 1'd1);

assign p_Result_66_fu_571_p2 = (num1 & lshr_ln628_1_fu_565_p2);

assign p_Result_67_fu_600_p2 = (shl_ln368_fu_588_p2 & shl_ln368_1_fu_594_p2);

assign p_Result_68_fu_671_p2 = (num2 & lshr_ln628_3_fu_665_p2);

assign p_Result_69_fu_706_p2 = (shl_ln368_3_fu_700_p2 & shl_ln368_2_fu_694_p2);

assign p_Result_71_fu_769_p1 = data_V_fu_748_p1[51:0];

assign p_Result_73_fu_894_p1 = data_V_1_fu_873_p1[51:0];

always @ (*) begin
    p_Result_74_fu_1204_p4 = result_V_reg_275;
    p_Result_74_fu_1204_p4[sext_ln288_1_fu_1187_p1] = |(p_Repl2_5_fu_1198_p2);
end

assign p_Result_75_fu_1258_p2 = (shl_ln368_5_fu_1252_p2 | and_ln368_1_fu_1242_p2);

assign r_V_22_fu_837_p2 = zext_ln15_fu_783_p1 << zext_ln1488_fu_827_p1;

assign r_V_23_fu_956_p2 = zext_ln15_1_fu_908_p1 >> zext_ln1488_1_fu_952_p1;

assign r_V_24_fu_962_p2 = zext_ln15_1_fu_908_p1 << zext_ln1488_1_fu_952_p1;

assign r_V_26_fu_1266_p2 = grp_decoder_Pipeline_decoder_label10_fu_364_sum_V_2_out << 29'd1;

assign r_V_fu_831_p2 = zext_ln15_fu_783_p1 >> zext_ln1488_fu_827_p1;

assign result_V_5_fu_1006_p2 = (32'd0 - val_reg_1535);

assign result_V_8_fu_1017_p2 = (32'd0 - val_1_reg_1546);

assign select_ln40_fu_487_p3 = ((targetBlock_reg_1446[0:0] == 1'b1) ? 6'd63 : in_1_loc_fu_210);

assign select_ln78_fu_613_p3 = ((targetBlock8_reg_1451[0:0] == 1'b1) ? 6'd63 : in_2_loc_fu_202);

assign sext_ln125_fu_732_p1 = k1_2_reg_1456;

assign sext_ln126_fu_736_p1 = k2_4_reg_1487;

assign sext_ln1488_1_fu_948_p1 = $signed(ush_3_fu_940_p3);

assign sext_ln1488_fu_823_p1 = $signed(ush_fu_815_p3);

assign sext_ln1512_1_fu_936_p1 = $signed(sub_ln1512_1_fu_930_p2);

assign sext_ln1512_fu_811_p1 = $signed(sub_ln1512_fu_805_p2);

assign sext_ln288_1_fu_1187_p1 = opposite_bit_index_final_reg_1647;

assign sext_ln288_fu_1173_p1 = $signed(abs_fu_1165_p3);

assign shl_ln368_1_fu_594_p2 = 28'd268435455 << zext_ln368_1_fu_584_p1;

assign shl_ln368_2_fu_694_p2 = tmp_33_fu_676_p1 << zext_ln368_2_fu_686_p1;

assign shl_ln368_3_fu_700_p2 = 28'd268435455 << zext_ln368_3_fu_690_p1;

assign shl_ln368_4_fu_1230_p2 = 32'd3 << zext_ln368_4_fu_1226_p1;

assign shl_ln368_5_fu_1252_p2 = zext_ln368_5_fu_1248_p1 << zext_ln368_4_fu_1226_p1;

assign shl_ln368_fu_588_p2 = tmp_32_fu_576_p1 << zext_ln368_fu_580_p1;

assign sub228_fu_1140_p2 = (5'd0 - trunc_ln256_fu_1117_p1);

assign sub_ln103_fu_680_p2 = ($signed(5'd30) - $signed(trunc_ln779_1_fu_624_p1));

assign sub_ln1512_1_fu_930_p2 = (11'd1023 - xs_exp_V_1_fu_884_p4);

assign sub_ln1512_fu_805_p2 = (11'd1023 - xs_exp_V_fu_759_p4);

assign sub_ln153_fu_1086_p2 = (32'd28 - exp1_conv_reg_1558);

assign sub_ln628_1_fu_655_p2 = (5'd2 - trunc_ln99_fu_651_p1);

assign sub_ln628_fu_555_p2 = (5'd2 - trunc_ln61_fu_545_p1);

assign sub_ln66_fu_549_p2 = ($signed(5'd30) - $signed(trunc_ln779_fu_498_p1));

assign tmp_28_fu_968_p3 = r_V_23_fu_956_p2[32'd53];

assign tmp_29_fu_1121_p3 = k_final_fu_1111_p3[32'd5];

assign tmp_2_fu_980_p4 = {{r_V_24_fu_962_p2[84:53]}};

assign tmp_30_fu_1190_p3 = result_V_reg_275[32'd30];

assign tmp_32_fu_576_p1 = p_Result_66_fu_571_p2[27:0];

assign tmp_33_fu_676_p1 = p_Result_68_fu_671_p2[27:0];

assign tmp_fu_843_p3 = r_V_fu_831_p2[32'd53];

assign tmp_s_fu_855_p4 = {{r_V_22_fu_837_p2[84:53]}};

assign trunc_ln256_1_fu_1135_p1 = k_final_1_fu_1129_p2[4:0];

assign trunc_ln256_fu_1117_p1 = k_final_fu_1111_p3[4:0];

assign trunc_ln297_fu_1183_p1 = opposite_bit_index_final_fu_1177_p2[4:0];

assign trunc_ln60_fu_521_p1 = select_ln40_fu_487_p3[4:0];

assign trunc_ln61_fu_545_p1 = select_ln40_fu_487_p3[4:0];

assign trunc_ln779_1_fu_624_p1 = select_ln78_fu_613_p3[4:0];

assign trunc_ln779_fu_498_p1 = select_ln40_fu_487_p3[4:0];

assign trunc_ln98_fu_628_p1 = select_ln78_fu_613_p3[4:0];

assign trunc_ln99_fu_651_p1 = select_ln78_fu_613_p3[4:0];

assign ush_3_fu_940_p3 = ((isNeg_2_fu_922_p3[0:0] == 1'b1) ? sext_ln1512_1_fu_936_p1 : add_ln515_1_fu_916_p2);

assign ush_fu_815_p3 = ((isNeg_fu_797_p3[0:0] == 1'b1) ? sext_ln1512_fu_811_p1 : add_ln515_fu_791_p2);

assign val_1_fu_990_p3 = ((isNeg_2_fu_922_p3[0:0] == 1'b1) ? zext_ln818_1_fu_976_p1 : tmp_2_fu_980_p4);

assign val_fu_865_p3 = ((isNeg_fu_797_p3[0:0] == 1'b1) ? zext_ln818_fu_851_p1 : tmp_s_fu_855_p4);

assign xor_ln368_fu_1236_p2 = (shl_ln368_4_fu_1230_p2 ^ 32'd4294967295);

assign xs_exp_V_1_fu_884_p4 = {{data_V_1_fu_873_p1[62:52]}};

assign xs_exp_V_fu_759_p4 = {{data_V_fu_748_p1[62:52]}};

assign zext_ln1488_1_fu_952_p1 = $unsigned(sext_ln1488_1_fu_948_p1);

assign zext_ln1488_fu_827_p1 = $unsigned(sext_ln1488_fu_823_p1);

assign zext_ln15_1_fu_908_p1 = mantissa_1_fu_898_p4;

assign zext_ln15_fu_783_p1 = mantissa_fu_773_p4;

assign zext_ln368_1_fu_584_p1 = sub_ln66_fu_549_p2;

assign zext_ln368_2_fu_686_p1 = sub_ln103_fu_680_p2;

assign zext_ln368_3_fu_690_p1 = sub_ln103_fu_680_p2;

assign zext_ln368_4_fu_1226_p1 = add_ln368_fu_1221_p2;

assign zext_ln368_5_fu_1248_p1 = exponent_arr_V_2_reg_254;

assign zext_ln368_fu_580_p1 = sub_ln66_fu_549_p2;

assign zext_ln515_1_fu_912_p1 = xs_exp_V_1_fu_884_p4;

assign zext_ln515_fu_787_p1 = xs_exp_V_fu_759_p4;

assign zext_ln628_1_fu_561_p1 = sub_ln628_fu_555_p2;

assign zext_ln628_2_fu_638_p1 = add_ln628_1_fu_632_p2;

assign zext_ln628_3_fu_661_p1 = sub_ln628_1_fu_655_p2;

assign zext_ln628_fu_531_p1 = add_ln628_fu_525_p2;

assign zext_ln818_1_fu_976_p1 = tmp_28_fu_968_p3;

assign zext_ln818_fu_851_p1 = tmp_fu_843_p3;

always @ (posedge ap_clk) begin
    r_V_26_reg_1670[0] <= 1'b0;
end

endmodule //decoder
